"""Add organization invites

Revision ID: 2ed4dbd5ebc0
Revises: 0002
Create Date: 2026-08-13 21:57:29.491597
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '2ed4dbd5ebc0'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_invites',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("role IN ('admin', 'editor', 'viewer')", name=op.f('ck_organization_invites_ck_org_invites_role_valid')),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'rejected', 'revoked')", name=op.f('ck_organization_invites_ck_org_invites_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_organization_invites_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_organization_invites_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_invites')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_organization_invites_token_hash'))
    )
    op.create_index('ix_org_invites_email_status', 'organization_invites', ['email', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_org_invites_email_status', table_name='organization_invites')
    op.drop_table('organization_invites')
    # ### end Alembic commands ###
